project:
  type: website
  output-dir: docs

website:
  title: "quarto_website"
  navbar:
    title: "Owen's Website"
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: blog/project1/project1_index.qmd
        text: Projects

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
